export const AVAILABLE_TERMS = [
  'abracadabra',
  'adventureland',
  'animal kingdom',
  'anna',
  'ariel',
  'aurora',
  'balloon',
  'belle',
  'beverly',
  'bibbidi bobbidi',
  'big thunder mountain',
  'california adventure',
  'carousel of progress',
  'castle',
  'churro',
  'cinderella',
  'confectionary',
  'contemporary',
  'corn dog',
  'creation',
  'daisy',
  'disney springs',
  'disney world',
  'disneyland',
  'dole whip',
  'donald',
  'downtown disney',
  'dumbo',
  'elsa',
  'enchantment',
  'epcot',
  'expedition everest',
  'fantasmic',
  'fantasy',
  'festival of the arts',
  'figment',
  'fireworks',
  'flower and garden',
  'food and wine',
  'friendship boats',
  'frontierland ',
  'goofy',
  'grand californian',
  'grand floridian',
  'great wilderness',
  'happily ever after',
  'haunted mansion',
  'hollywood studios',
  'imagination',
  'jasmine',
  "joffrey's",
  'loungefly',
  'magic',
  'magic kingdom',
  'main street',
  'merida',
  'mickey',
  'millenium falcon',
  'minnie',
  'moana',
  'monorail',
  'mulan',
  "na'vi river",
  'not-so-scary',
  'ohana',
  'parade',
  'party',
  'peoplemover',
  'peterpan',
  'pirate',
  'pluto',
  'pocahontas',
  'popcorn',
  'dolewhip',
  'pretzel',
  'rapunzel',
  'rose',
  'roundup rodeo',
  'runaway railway',
  'skyliner',
  'slinky dog',
  'small world',
  'snow white',
  'soarin',
  'space mountain',
  'spaceship earth',
  'speedway',
  'splash mountain',
  'starjumper ',
  'test track',
  'tiana',
  'tomorrowland',
  'tree of life',
  'tron',
  'very merry',
  'walt',
  'wish',
  'wonder',
  'world showcase',
];

export const MAGIC_IPSUM_STARTER = 'Magic ipsum dolor sit amet ';
